steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${_FIREBASE_PROJECT_ID}/firebase',
        './dockerfiles/firebase',
      ]

  # Install node deps
  - name: 'node:16.20'
    entrypoint: 'yarn'

  # Build/Deploy all projects
  - name: 'node:16.20'
    entrypoint: 'yarn'
    args: ['nx', 'run-many', '-t', 'deploy', '--token', '${_FIREBASE_TOKEN}']

timeout: 1200s
