steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${_FIREBASE_PROJECT_ID}/firebase',
        './dockerfiles/firebase',
      ]

  # Install node deps
  - name: 'node:18.17'
    entrypoint: 'yarn'

  # Build/Deploy back-office
  - name: 'node:18.17'
    entrypoint: 'yarn'
    args: ['nx', 'deploy', 'back-office', '--token', '${_FIREBASE_TOKEN}']

timeout: 1200s
