steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${_FIREBASE_PROJECT_ID}/firebase',
        './dockerfiles/firebase',
      ]

  # Install node deps
  - name: 'node:16.20'
    entrypoint: 'yarn'

  # Build/Deploy front-office
  - name: 'node:16.20'
    entrypoint: 'yarn'
    args: ['nx', 'deploy', 'front-office', '--token', '${_FIREBASE_TOKEN}']
    env:
      - 'VITE_API_URL=${_API_URL}'
      - 'VITE_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'VITE_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'VITE_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'VITE_FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - 'VITE_CLOUD_MESSAGING_PUBLIC_VAPID_KEY=${_CLOUD_MESSAGING_PUBLIC_VAPID_KEY}'
      - 'VITE_MESSAGING_SENDER_ID=${_MESSAGING_SENDER_ID}'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'VITE_FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}'
      - 'VITE_FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}'


timeout: 1200s

